- git: >
    repo=https://github.com/Stulikov/backdoor.git
    dest=/home/pi/doorway
    version=master
    force=yes
  become: yes
  become_user: pi

- command: systemctl restart backdoor
  become: yes
